[window]
padding = { x = 6, y = 6 }
decorations = "none"

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[font]
size = 19.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[keyboard]

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\\x1b\r"
